/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlogEntryWizard: typeof import('./components/BlogEntryWizard.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    GpxMap: typeof import('./components/GpxMap.vue')['default']
    HikeMovementBreakdown: typeof import('./components/HikeMovementBreakdown.vue')['default']
    HikeStatsChart: typeof import('./components/HikeStatsChart.vue')['default']
    HillDetails: typeof import('./components/HillDetails.vue')['default']
    HillProgress: typeof import('./components/HillProgress.vue')['default']
    MiniLocationMap: typeof import('./components/MiniLocationMap.vue')['default']
    PeakMap: typeof import('./components/PeakMap.vue')['default']
    PostCard: typeof import('./components/PostCard.vue')['default']
    PostSelector: typeof import('./components/select/PostSelector.vue')['default']
    PostStepContent: typeof import('./components/steps/PostStepContent.vue')['default']
    PostStepEntryType: typeof import('./components/steps/PostStepEntryType.vue')['default']
    PostStepGpx: typeof import('./components/steps/PostStepGpx.vue')['default']
    PostStepMedia: typeof import('./components/steps/PostStepMedia.vue')['default']
    PostStepPeaks: typeof import('./components/steps/PostStepPeaks.vue')['default']
    PostStepReview: typeof import('./components/steps/PostStepReview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteDetails: typeof import('./components/SiteDetails.vue')['default']
    SiteMap: typeof import('./components/SiteMap.vue')['default']
    StoryCard: typeof import('./components/StoryCard.vue')['default']
    StoryEntryWizard: typeof import('./components/StoryEntryWizard.vue')['default']
    StoryStepContent: typeof import('./components/steps/StoryStepContent.vue')['default']
    StoryStepEntryType: typeof import('./components/steps/StoryStepEntryType.vue')['default']
    StoryStepPosts: typeof import('./components/steps/StoryStepPosts.vue')['default']
    StoryStepReview: typeof import('./components/steps/StoryStepReview.vue')['default']
    YoutubeVideo: typeof import('./components/YoutubeVideo.vue')['default']
  }
}
