/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hill/': RouteRecordInfo<
      '/hill/',
      '/hill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hill/[id]': RouteRecordInfo<
      '/hill/[id]',
      '/hill/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/post/': RouteRecordInfo<
      '/post/',
      '/post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/post/[id]/': RouteRecordInfo<
      '/post/[id]/',
      '/post/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/post/[id]/edit': RouteRecordInfo<
      '/post/[id]/edit',
      '/post/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/post/create': RouteRecordInfo<
      '/post/create',
      '/post/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/site/': RouteRecordInfo<
      '/site/',
      '/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/site/[id]': RouteRecordInfo<
      '/site/[id]',
      '/site/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/story/': RouteRecordInfo<
      '/story/',
      '/story',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/story/[id]/': RouteRecordInfo<
      '/story/[id]/',
      '/story/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/story/[id]/edit': RouteRecordInfo<
      '/story/[id]/edit',
      '/story/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/story/create': RouteRecordInfo<
      '/story/create',
      '/story/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hill/index.vue': {
      routes:
        | '/hill/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hill/[id].vue': {
      routes:
        | '/hill/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/post/index.vue': {
      routes:
        | '/post/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/post/[id]/index.vue': {
      routes:
        | '/post/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/post/[id]/edit.vue': {
      routes:
        | '/post/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/post/create.vue': {
      routes:
        | '/post/create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/site/index.vue': {
      routes:
        | '/site/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/site/[id].vue': {
      routes:
        | '/site/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/story/index.vue': {
      routes:
        | '/story/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/story/[id]/index.vue': {
      routes:
        | '/story/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/story/[id]/edit.vue': {
      routes:
        | '/story/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/story/create.vue': {
      routes:
        | '/story/create'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
